# Generated by Django 3.0.2 on 2020-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200304_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='preview_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
