# Generated by Django 3.0.2 on 2020-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200304_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='preview_image',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
